version: "3"
services:
  app-user-db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "App_user_mssql_pass123!"
      MSSQL_PID: Express
    ports: 
      - "1433:1433"
  seq-logs:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:5341"
  apigateway:
    build: ./ApiGateway
    ports:
      - "5000:80"
    environment:
      - APPUSERDB_CONNECTION_STRING: "Server=app-user-name;Database=AppUserDb;Trusted_Connection=true",
      - APP_ADMIN_USER: "onurbpm@oulook.com",
      - APP_ADMIN_PASSWORD: "testparola123"
    depends_on:
      - app-user-db
      - seq-logs
