version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
  kibana:
    image: docker.elastic.co/kibana/kibana:latest
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  app-user-db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - "1433:1433"
  apigateway:
    build: ./ApiGateway
    ports:
      - "5000:5000"
    env_file:
      - ./ApiGateway/dev-docker.env
    depends_on:
      - app-user-db
      - kibana
