version: "3.4"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
  seq-log:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
  apigateway:
    build: ./ApiGateway
    ports:
      - "5000:5000"
    env_file:
      - ./ApiGateway/dev-docker.env
    depends_on:
      - db
      - seq-log
